#!/bin/bash

#while getopts ":R" opt; do
#  case $opt in
#    R) RUNFOLDER=$OPTARG;;
#    \?)
#      echo "Invalid option: -$OPTARG" >&2
#      ;;
#  esac
#done

COMMANDS="commands"
PREFIX=$(basename $(pwd)) #prefix for the filenames of the split commands
COMMANDSSPLIT="commands-split"
COMMANDSSUBMISSION="commands-submission"
WAITTIME=1800

#split the list of commands into files
split -1 $COMMANDS $PREFIX

#write the filenames into the split-commands file
ls $PREFIX* > $COMMANDSSPLIT

#concatenate qsub command to the filenames and write to the submmission file
sed 's/^/qsub -cwd  -l  qname=gale.q  /' $COMMANDSSPLIT > $COMMANDSSUBMISSION

jobs_in_q=0

#read the jobs in the submissions file 
while read job ; do 
  jobs_in_q=$(qstat -f | grep $PREFIX | wc -l)
  until [ $jobs_in_q -lt  3 ] ; do
    #echo "too many jobs in queue. waiting..."
    sleep $WAITTIME
    #echo "checking jobs..."
    jobs_in_q=$(qstat -f | grep $PREFIX | wc -l)
    #echo $jobs_in_q
  done
  #echo "jobs < 3"
  date "+%Y%m%d %H:%M:%S.%N"
  $job
done < $COMMANDSSUBMISSION
echo "All jobs submitted."
