#!/bin/bash
#takes a list of directories and makes a list of
#rsync commands

SEGMENT="1000"

CLOUD_PW="~/.cloud"

#OBERON PATH
CLOUD_PW="/gale/netapp/home/seq/.cloud"

COMMAND="java -jar /gale/netapp/home/seq/uploadcli.jar -segment-size $SEGMENT -archive -overwrite -url  https://a429964.storage.oraclecloud.com/v1/Storage-a429964 -service Storage -user gale@salk.edu -password-file $CLOUD_PW -container gale-netapp-seq4 -segments-container gale-netapp-seq4"

usage() {
echo "Usage: list2tar -l list -s /gale/netapp/seq2/illumina_runs -d /gale/oberon/data2 -e tar.gz"
echo "-l        file containing a list of directories or files"
echo "-s        path to source parent directory where files reside"
#echo "-d        path to destination parent directory"
echo "-e        extension for files in the list if applicable (example tar.gz)"
echo "-h        display this help message"
}

while getopts ":l:s:d:e:h" opt; do
  case $opt in
    l) LISTFILE=$OPTARG;;
    s) SRC=$OPTARG;;
    d) DEST=$OPTARG;;
    e) EXT=$OPTARG;;
    h)
      usage
      exit 1;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      ;;
  esac
done

while read run_folder
  do
    if [ -z "$EXT" ]
    then
      echo "$COMMAND $SRC/$run_folder"
    else
      echo "$COMMAND $SRC/$run_folder.$EXT 2> ./$run_folder.e" # > ./$run_folder.log"
    fi
done < $LISTFILE

#java -jar /gale/netapp/home/seq/uploadcli.jar -segment-size 500 -archive -overwrite -url  https://a429964.storage.oraclecloud.com/v1/Storage-a429964 -service Storage -user gale@salk.edu -password-file ~/.cloud -container gale-netapp-seq4 -segments-container gale-netapp-seq4 /gale/gale_temp/seq2/151028_BARB_4099_AH2M5JBBXX.tar.gz
