#!/bin/bash
#takes a list of directories and makes a list of
#rsync commands

LISTFILE="$1"
COMMAND="rsync -avsz" # -i -h"
#SRC="/gale/netapp/seq2/illumina_runs" #path to parent of source dir
SRC="/gale/netapp/scratch"
#DEST="/gale/oberon/data11" #dir to copy source into
DEST="/gale/oberon/data2"
#LOG_PARENT="/gale/netapp/home/seq/logs/seq2/rsync"
LOG_PARENT="/gale/netapp/home/seq/logs/scratch/rsync"
DATE="181106"
PART1="./script-template/part1"
PART2="./script-template/part2"


usage() {
echo "Usage: list2methylpy -l list -r R1"
echo "-l        file containing a list of directories or files"
echo "-r        read id, eg R1"
echo "-h        display this help message"
}

READ="R1"

while getopts ":l:s:r:L:h" opt; do
  case $opt in
    l) LISTFILE=$OPTARG;;
    s) SRC=$OPTARG;;
    r) READ=$OPTARG;;
    h)
      usage
      exit 1;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      ;;
  esac
done

echo "READID=\"$READ\"" > READSTRING

while read folder
    do echo "SAMPLEID=\"$folder\"" > samplestring
      cat $PART1 READSTRING samplestring $PART2 > $folder"_"$READ.sh
done < $LISTFILE

rm READSTRING
rm samplestring
