#!/bin/bash
#takes a list of directories and makes a list of
#rsync commands

LISTFILE="$1"
COMMAND="rsync -avsz" # -i -h"
#SRC="/gale/netapp/seq2/illumina_runs" #path to parent of source dir
SRC="/gale/netapp/scratch"
#DEST="/gale/oberon/data11" #dir to copy source into
DEST="/gale/oberon/data2"
#LOG_PARENT="/gale/netapp/home/seq/logs/seq2/rsync"
LOG_PARENT="/gale/netapp/home/seq/logs/scratch/rsync"
DATE="181106"
PART1="./script-template/part1"
PART2="./script-template/part2"

PREFIX="190214_Nathans_EC_mm_"
SUFFIX="_snmCseq_Novaseq_pe_150_CL"


usage() {
echo "Usage: list2rsync -l list -s /gale/netapp/seq2/illumina_runs -d /gale/oberon/data2"
echo "-l        file containing a list of directories or files"
#echo "-s        path to source parent directory where files reside"
#echo "-d        path to destination parent directory"
#echo "-r        read id, eg R1"
echo "-h        display this help message"
}

#READ="R1"

while getopts ":l:s:d:r:L:h" opt; do
  case $opt in
    l) LISTFILE=$OPTARG;;
    s) SRC=$OPTARG;;
    d) DEST=$OPTARG;;
    r) READ=$OPTARG;;
    L) LOG=$OPTARG;;
    h)
      usage
      exit 1;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      ;;
  esac
done

while read folder
    do echo "SAMPLEID=\"$folder\"" > samplestring
      cat $PART1 samplestring $PART2 > $PREFIX$folder$SUFFIX.sh
done < $LISTFILE

rm samplestring
