#!/bin/bash
#takes a list of directories and makes a list of
#rsync commands

LISTFILE="$1"
COMMAND="gunzip -c" # -i -h"
#SRC="/gale/netapp/seq2/illumina_runs" #path to parent of source dir
SRC="/gale/netapp/scratch"
#DEST="/gale/oberon/data11" #dir to copy source into
DEST="/gale/oberon/data2"
#LOG_PARENT="/gale/netapp/home/seq/logs/seq2/rsync"
LOG_PARENT="/gale/netapp/home/seq/logs/scratch/rsync"
DATE="181106"

usage() {
echo "Usage: list2rsync -l list -s /gale/netapp/seq2/illumina_runs -d /gale/oberon/data2"
echo "-l        file containing a list of directories or files"
echo "-s        path to source parent directory where files reside"
echo "-d        path to destination parent directory"
#echo "-e        extension for files in the list if applicable"
echo "-h        display this help message"
}

while getopts ":l:s:d:e:L:h" opt; do
  case $opt in
    l) LISTFILE=$OPTARG;;
    s) SRC=$OPTARG;;
    d) DEST=$OPTARG;;
    e) EXT=$OPTARG;;
    L) LOG=$OPTARG;;
    h)
      usage
      exit 1;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      ;;
  esac
done

while read folder
   do echo "$COMMAND $SRC/$folder > $DEST/$(basename $folder .gz)"
done < $LISTFILE

#You can think of a trailing / on a source as meaning 
#"copy the contents of this directory" as opposed to 
#"copy the directory by name"

