#!/bin/bash
#date="$(basename $(pwd) | awk -F"-" '{print substr($NF,1,6)}')"
DATE="$(date +%y%m%d)"
#IN="/archive/gale-netapp/seq2/illumina_runs"
##OUT="/data/home/seq/logs/seq2"

archived="/archive/oberon/data4/.archived"

usage() {
echo "Usage: list2tape -l list -s /archive/gale-netapp/seq2/illumina_runs -L /data/home/seq/logs/seq2"
echo "-l        file containing a list of directories or files"
echo "-s        path to source parent directory where files reside"
#echo "-d        path to destination parent directory"
#echo "-e        extension for files in the list if applicable"
echo "-h        display this help message"
}

while getopts ":l:s:d:e:L:h" opt; do
  case $opt in
    l) LISTFILE=$OPTARG;;
    s) SRC=$OPTARG;;
    e) EXT=$OPTARG;;
    L) LOG=$OPTARG;;
    h)
      usage
      exit 1;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      ;;
  esac
done

while read run_folder
   do echo $run_folder | grep -q M00 && \
   echo "sudo dsmc ar -subdir=yes $SRC/$run_folder/ &> $LOG/$DATE/$run_folder.txt && echo $run_folder >> $archived && sleep 7200" || \
   echo "sudo dsmc ar -subdir=yes $SRC/$run_folder/ &> $LOG/$DATE/$run_folder.txt && echo $run_folder >> $archived && sleep 14400" 
done < $LISTFILE

